import Head from 'next/head'


import Header from './components/Header'
import Feature from './components/Feature'
import { connect } from './lib/mongoose'
import { Product } from './lib/products'

export default function Home({product}) {
  return (
    <div className=' max-w-7xl mx-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      <Header/>
      
      <Feature data={product}/>

      </main>

     
    </div>
  )
}

export async function getServerSideProps() {
  const featuredId =  "6474cd6e46b89b5d43bc7318"
  await connect()
  const product = await Product.findById(featuredId)
  return {  
    props: {product:JSON.parse (JSON.stringify(product))}
  }

}
