import Head from 'next/head'


import Header from './components/Header'
import Feature from './components/Feature'
import AllProducts from './components/AllProducts'
import { connect } from './lib/mongoose'
import { Product } from './lib/products'

export default function Home({product,allProducts}) {
  return (
    <div className=' max-w-7xl mx-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      <Header/>
      <Feature data={product}/>
      <AllProducts data={allProducts}/>

      </main>

     
    </div>
  )
}

export async function getServerSideProps() {
  const featuredId =  "6474cd6e46b89b5d43bc7318"
  await connect()
  const product = await Product.findById(featuredId)
  const allProducts = await Product.find({},null,{sort:{updatedAt:-1}})
  return {  
    props: {
      allProducts:JSON.parse (JSON.stringify(allProducts)),
      product:JSON.parse (JSON.stringify(product))}
  }

}
